# .streamlit/secrets.toml

[credentials]

  [credentials.usernames.john_doe]
  email = "john@example.com"
  name = "John Doe"
  password = "$2b$12$ZNBXi3bsN1BJhkf4ELTAbeNfNsJQMTXSGnTyqvrosc.Pet1I40DFO"

  [credentials.usernames.jane_smith]
  email = "jane@example.com"
  name = "Jane Smith"
  password = "$2b$12$q/bsD.nvLubxf/D7Un5jyuDeoV8Zzx3EyHxylz3oZODpNnpTEiPaq"

[cookie]
name = "some_cookie_name"
key = "some_signature_key"
expiry_days = 30

[preauthorized]
# (Optional) If you want certain users to skip login
emails = ["john@example.com"]
